## TG Classificação ESG Leitura e Tratamento da Origem dos dados

#### Leitura da base de dados do S&P 500 diretamento do Yahoo Finance utilizando a biblioteca yfinance, que em seguida será exportado para CSV

import pandas as pd
import yfinance as yf
import time

# 1. Captura a lista de empresas do S&P 500 da Wikipedia
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
tabela = pd.read_html(url)
sp500_df = tabela[0]
tickers = sp500_df['Symbol'].tolist()

# Corrige tickers com ponto
tickers = [ticker.replace('.', '-') for ticker in tickers]

# 2. Coleta todas as informações disponíveis de cada empresa
def get_all_info(ticker):
    try:
        info = yf.Ticker(ticker).info
        info['Ticker'] = ticker  # adiciona a identificação
        return info
    except Exception as e:
        print(f"Erro com {ticker}: {e}")
        return None

# 3. Loop para coletar os dados
dados_completos = []
for ticker in tickers:
    print(f"Coletando: {ticker}")
    data = get_all_info(ticker)
    if data:
        dados_completos.append(data)
    time.sleep(1)  # pausa para evitar bloqueio da API

# 4. Criar DataFrame com todas as colunas possíveis
df_completo = pd.DataFrame(dados_completos)

# 5. Exportar
df_completo.to_excel('sp500_dados_completos.xlsx', index=False)
df_completo.to_csv('sp500_dados_completos.csv', index=False)

print("Coleta completa finalizada.")

In [ ]:
import yfinance as yf
import pandas as pd
import time

# Lista de tickers (sua lista completa)
tickers_personalizados = [
    "ENPH", "EMN", "DPZ", "DAY", "DVA", "DRI", "ZTS", "ZBH", "ZBRA", "YUM", "XYL", "XEL", "WYNN", "WTW", "WMB", "WY",
    "WRK", "WDC", "WST", "WELL", "WFC", "WEC", "WAT", "WM", "WBD", "WMT", "WBA", "WAB", "GWW", "WRB", "VMC", "VST", "V",
    "VICI", "VTRS", "VRTX", "VZ", "VRSK", "VRSN", "VLTO", "VTR", "VLO", "UHS", "UNH", "URI", "UPS", "UAL", "UNP", "ULTA",
    "UDR", "UBER", "USB", "TSN", "TYL", "TFC", "TRMB", "TDG", "TT", "TSCO", "TJX", "TMO", "DIS", "TRV", "SO", "SHW", "MOS",
    "KR", "KHC", "SJM", "IPG", "HSY", "HIG", "EL", "COO", "CI", "SCHW", "ALL", "TXT", "TXN", "TSLA", "TER", "TFX", "TDY",
    "TEL", "TGT", "TRGP", "TPR", "TTWO", "TMUS", "TROW", "SYY", "SNPS", "SYF", "SMCI", "SYK", "STE", "STLD", "STT", "SBUX",
    "SWK", "LUV", "SOLV", "SNA", "SWKS", "SPG", "NOW", "SRE", "STX", "SLB", "SBAC", "CRM", "SPGI", "RTX", "RCL", "ROST",
    "ROP", "ROL", "ROK", "RHI", "RVTY", "RMD", "RSG", "RF", "REGN", "REG", "O", "RJF", "RL", "DGX", "PWR", "QCOM", "QRVO",
    "PHM", "PSA", "PEG", "PTC", "PRU", "PLD", "PGR", "PG", "PFG", "PPL", "PPG", "POOL", "PNC", "PNW", "PSX", "PM", "PCG",
    "PFE", "PEP", "PNR", "PYPL", "PAYC", "PAYX", "PH", "PARA", "PANW", "PKG", "PCAR", "OTIS", "ORCL", "OKE", "ON", "OMC",
    "ODFL", "OXY", "ORLY", "NXPI", "NVR", "NVDA", "NUE", "NRG", "NCLH", "NOC", "NTRS", "NSC", "NDSN", "NI", "NKE", "NEE",
    "NWS", "NWSA", "NEM", "NFLX", "NTAP", "NDAQ", "MSCI", "MSI", "MS", "MCO", "MNST", "MPWR", "MDLZ", "TAP", "MOH", "MHK",
    "MRNA", "MAA", "MSFT", "MU", "MCHP", "MGM", "MTD", "MET", "META", "MRK", "MDT", "MCK", "MCD", "MKC", "MTCH", "MA",
    "MAS", "MLM", "MMC", "MAR", "MKTX", "MPC", "MRO", "MTB", "LYB", "LULU", "LOW", "L", "LMT", "LKQ", "LYV", "LIN", "LEN",
    "LDOS", "LVS", "LW", "LRCX", "LH", "LHX", "KLAC", "KMI", "KIM", "KMB", "KEYS", "KEY", "KDP", "KVUE", "K", "JNPR", "JPM",
    "JCI", "JNJ", "JBHT", "J", "JBL", "IRM", "IQV", "INVH", "IVZ", "ISRG", "INTU", "IP", "IFF", "IBM", "ICE", "INTC", "PODD",
    "IR", "INCY", "ILMN", "ITW", "IDXX", "IEX", "HII", "HBAN", "HUM", "HUBB", "HPQ", "HWM", "HST", "HRL", "HON", "HD",
    "HOLX", "HLT", "HPE", "HES", "HSIC", "JKHY", "DOC", "HCA", "HAS", "HAL", "GS", "GL", "GPN", "GILD", "GPC", "GM", "GIS",
    "GE", "GD", "GNRC", "GEN", "GEV", "GEHC", "IT", "GRMN", "FCX", "BEN", "FOX", "FOXA", "FTV", "FTNT", "F", "FMC", "FI",
    "FE", "FSLR", "FITB", "FIS", "FDX", "FRT", "FAST", "FICO", "FDS", "FFIV", "XOM", "EXR", "EXPD", "EXPE", "EXC", "ES",
    "EVRG", "EG", "ETSY", "ESS", "EQR", "EQIX", "EFX", "EQT", "EPAM", "EOG", "ETR", "EMR", "LLY", "ELV", "EA", "EW", "EIX",
    "ECL", "EBAY", "ETN", "DD", "DUK", "DTE", "DOW", "DOV", "D", "DLTR", "DG", "DFS", "DLR", "FANG", "DXCM", "DVN", "DAL",
    "DE", "DECK", "DHR", "DHI", "CVS", "CMI", "CSX", "CCI", "CTRA", "COST", "CSGP", "CTVA", "CPAY", "GLW", "CPRT", "CEG",
    "STZ", "ED", "COP", "CAG", "CMA", "CMCSA", "CL", "CTSH", "KO", "CMS", "CME", "CLX", "CFG", "C", "CSCO", "CTAS", "CINF",
    "CHD", "CB", "CMG", "CVX", "CHTR", "CRL", "CF", "CNP", "CNC", "COR", "CE", "CDW", "CBRE", "CBOE", "CAT", "CTLT", "CARR",
    "CCL", "KMX", "CAH", "COF", "CPB", "CPT", "CZR", "CDNS", "CHRW", "BG", "BLDR", "BF.B", "BRO", "BR", "AVGO", "BMY", "BSX",
    "BXP", "BWA", "BKNG", "BA", "BX", "BLK", "BIIB", "TECH", "BIO", "BBY", "BRK-B", "BDX", "BAX", "BBWI", "BK", "BAC",
    "BALL", "BKR", "AXON", "AVY", "AVB", "AZO", "ADP", "ADSK", "ATO", "T", "AIZ", "AJG", "ANET", "ADM", "ACGL", "APTV",
    "AMAT", "AAPL", "APA", "AON", "ANSS", "ADI", "APH", "AMGN", "AME", "AMP", "AWK", "AMT", "AIG", "AXP", "AEP", "AAL",
    "AEE", "AMCR", "AMZN", "MO", "GOOG", "GOOGL", "LNT", "ALLE", "ALGN", "ARE", "ALB", "AKAM", "ABNB", "APD", "A", "AFL",
    "AES", "AMD", "ADBE", "ACN", "ABBV", "ABT", "AOS", "MMM"
]

# Função para buscar todos os dados
def get_all_info(ticker):
    try:
        info = yf.Ticker(ticker).info
        info['Ticker'] = ticker
        return info
    except Exception as e:
        print(f"Erro com {ticker}: {e}")
        return None

# Coleta
dados_empresas = []
for ticker in tickers_personalizados:
    print(f"Coletando {ticker}")
    data = get_all_info(ticker)
    if data:
        dados_empresas.append(data)
    time.sleep(1)  # evitar sobrecarga da API

# Salvar CSV
df = pd.DataFrame(dados_empresas)
df.to_csv("dados_sp500.csv", index=False)
print("Arquivo salvo como dados_empresas_personalizadas.csv")

#### Leitura do CSV gerado a partir da leitura da base do Yahoo Finance

In [1]:
import pandas as pd

# Caminho completo para o CSV
caminho_arquivo = r'C:\Users\lucas\TG - ESG\Datasets\dados_sp500.csv'

# Ler o arquivo
df_yf = pd.read_csv(caminho_arquivo)

df_yf.head()

,address1,city,state,zip,country,phone,website,industry,industryKey,industryDisp,...,lastDividendDate,earningsGrowth,dividendDate,prevName,nameChangeDate,address2,underlyingSymbol,uuid,ipoExpectedDate,industrySymbol
0,47281 Bayside Parkway,Fremont,CA,94538,United States,707 774 7000,https://www.enphase.com,Solar,solar,Solar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,200 South Wilcox Drive,Kingsport,TN,37662,United States,423 229 2000,https://www.eastman.com,Specialty Chemicals,specialty-chemicals,Specialty Chemicals,...,1.741910e+09,0.130,1.751933e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30 Frank Lloyd Wright Drive,Ann Arbor,MI,48105,United States,734 930 3030,https://ir.dominos.com,Restaurants,restaurants,Restaurants,...,1.741910e+09,0.301,1.751242e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3311 East Old Shakopee Road,Minneapolis,MN,55425,United States,952 853 8100,https://www.dayforce.com,Software - Application,software-application,Software - Application,...,NaN,1.250,NaN,Ceridian HCM Holding Inc.,2025-05-24,NaN,NaN,NaN,NaN,NaN
4,2000 16th Street,Denver,CO,80202,United States,720-631-2100,https://www.davita.com,Medical Care Facilities,medical-care-facilities,Medical Care Facilities,...,NaN,-0.245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Vamos utilizar a função shape para verificar o formato do dataset.

In [2]:
df_yf.shape

(503, 189)

#### Como podemos ver, nosso dataset é composto de 503 amostras com 189 features cada. Vamos verificar agora o tipo de cara feature.

In [3]:
df_types = pd.DataFrame(df_yf.dtypes, columns=['Tipo de Dado'])

In [4]:
from IPython.display import display

# Forçar exibição completa
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.expand_frame_repr', False)

# Mostrar como tabela do notebook
display(df_types)

                                  Tipo de Dado
address1                                object
city                                    object
state                                   object
zip                                     object
country                                 object
phone                                   object
website                                 object
industry                                object
industryKey                             object
industryDisp                            object
sector                                  object
sectorKey                               object
sectorDisp                              object
longBusinessSummary                     object
fullTimeEmployees                      float64
companyOfficers                         object
auditRisk                              float64
boardRisk                              float64
compensationRisk                       float64
shareHolderRightsRisk                  float64
overallRisk                            float64
governanceEpochDate                    float64
compensationAsOfEpochDate              float64
executiveTeam                           object
maxAge                                 float64
priceHint                              float64
previousClose                          float64
open                                   float64
dayLow                                 float64
dayHigh                                float64
regularMarketPreviousClose             float64
regularMarketOpen                      float64
regularMarketDayLow                    float64
regularMarketDayHigh                   float64
payoutRatio                            float64
beta                                   float64
trailingPE                             float64
forwardPE                              float64
volume                                 float64
regularMarketVolume                    float64
averageVolume                          float64
averageVolume10days                    float64
averageDailyVolume10Day                float64
bid                                    float64
ask                                    float64
bidSize                                float64
askSize                                float64
marketCap                              float64
fiftyTwoWeekLow                        float64
fiftyTwoWeekHigh                       float64
priceToSalesTrailing12Months           float64
fiftyDayAverage                        float64
twoHundredDayAverage                   float64
trailingAnnualDividendRate             float64
trailingAnnualDividendYield            float64
currency                                object
tradeable                               object
enterpriseValue                        float64
profitMargins                          float64
floatShares                            float64
sharesOutstanding                      float64
sharesShort                            float64
sharesShortPriorMonth                  float64
sharesShortPreviousMonthDate           float64
dateShortInterest                      float64
sharesPercentSharesOut                 float64
heldPercentInsiders                    float64
heldPercentInstitutions                float64
shortRatio                             float64
shortPercentOfFloat                    float64
impliedSharesOutstanding               float64
bookValue                              float64
priceToBook                            float64
lastFiscalYearEnd                      float64
nextFiscalYearEnd                      float64
mostRecentQuarter                      float64
netIncomeToCommon                      float64
trailingEps                            float64
forwardEps                             float64
enterpriseToRevenue                    float64
enterpriseToEbitda                     float64
52WeekChange                           float64
SandP52WeekChange                      float64
quoteType                               object
currentPrice                           float64
targetHighPrice                        float64
targetLowPrice                         float64
targetMeanPrice                        float64
targetMedianPrice                      float64
recommendationMean                     float64
recommendationKey                       object
numberOfAnalystOpinions                float64
totalCash                              float64
totalCashPerShare                      float64
ebitda                                 float64
totalDebt                              float64
quickRatio                             float64
currentRatio                           float64
totalRevenue                           float64
debtToEquity                           float64
revenuePerShare                        float64
returnOnAssets                         float64
returnOnEquity                         float64
grossProfits                           float64
freeCashflow                           float64
operatingCashflow                      float64
revenueGrowth                          float64
grossMargins                           float64
ebitdaMargins                          float64
operatingMargins                       float64
financialCurrency                       object
symbol                                  object
language                                object
region                                  object
typeDisp                                object
quoteSourceName                         object
triggerable                             object
customPriceAlertConfidence              object
marketState                             object
shortName                               object
longName                                object
corporateActions                        object
postMarketTime                         float64
regularMarketTime                      float64
exchange                                object
messageBoardId                          object
exchangeTimezoneName                    object
exchangeTimezoneShortName               object
gmtOffSetMilliseconds                  float64
market                                  object
esgPopulated                            object
regularMarketChangePercent             float64
regularMarketPrice                     float64
postMarketChangePercent                float64
postMarketPrice                        float64
postMarketChange                       float64
regularMarketChange                    float64
earningsTimestamp                      float64
earningsTimestampStart                 float64
earningsTimestampEnd                   float64
earningsCallTimestampStart             float64
earningsCallTimestampEnd               float64
isEarningsDateEstimate                  object
epsTrailingTwelveMonths                float64
epsForward                             float64
epsCurrentYear                         float64
priceEpsCurrentYear                    float64
fiftyDayAverageChange                  float64
fiftyDayAverageChangePercent           float64
twoHundredDayAverageChange             float64
twoHundredDayAverageChangePercent      float64
sourceInterval                         float64
exchangeDataDelayedBy                  float64
averageAnalystRating                    object
cryptoTradeable                         object
hasPrePostMarketData                    object
firstTradeDateMilliseconds             float64
regularMarketDayRange                   object
fullExchangeName                        object
averageDailyVolume3Month               float64
fiftyTwoWeekLowChange                  float64
fiftyTwoWeekLowChangePercent           float64
fiftyTwoWeekRange                       object
fiftyTwoWeekHighChange                 float64
fiftyTwoWeekHighChangePercent          float64
fiftyTwoWeekChangePercent              float64
displayName                             object
trailingPegRatio                       float64
Ticker                                  object
fax                                     object
irWebsite                               object
dividendRate                           float64
dividendYield                          float64
exDividendDate                         float64
fiveYearAvgDividendYield               float64
earningsQuarterlyGrowth                float64
lastSplitFactor                         object
lastSplitDate                          float64
lastDividendValue                      float64
lastDividendDate                       float64
earningsGrowth                         float64
dividendDate                           float64
prevName                                object
nameChangeDate                          object
address2                                object
underlyingSymbol                        object
uuid                                    object
ipoExpectedDate                         object
industrySymbol                          object

#### Forçando todas as colunas do DF a serem minusculas

In [5]:
df_yf.columns = df_yf.columns.str.lower()

#### Lendo base com clasificação de risco ESG

In [6]:
# Classificações de risco ESG SP 500
# Caminho do seu arquivo
caminho_arquivo_esg = r'C:\Users\lucas\TG - ESG\Datasets\SP 500 ESG Risk Ratings.csv'

# Leia o CSV em um DataFrame
df_esg = pd.read_csv(caminho_arquivo_esg)

df_esg.head()

  Symbol                      Name                                            Address             Sector                 Industry Full Time Employees                                        Description  Total ESG Risk score  Environment Risk Score  Governance Risk Score  Social Risk Score           Controversy Level  Controversy Score ESG Risk Percentile ESG Risk Level
0   ENPH      Enphase Energy, Inc.  47281 Bayside Parkway\nFremont, CA 94538\nUnit...         Technology                    Solar               3,157  Enphase Energy, Inc., together with its subsid...                   NaN                     NaN                    NaN                NaN                         NaN                NaN                 NaN            NaN
1    EMN  Eastman Chemical Company  200 South Wilcox Drive\nKingsport, TN 37662\nU...    Basic Materials      Specialty Chemicals              14,000  Eastman Chemical Company operates as a special...                  25.3                    12.8                    6.6                5.8  Moderate Controversy Level                2.0     50th percentile         Medium
2    DPZ       Domino's Pizza Inc.  30 Frank Lloyd Wright Drive\nAnn Arbor, MI 481...  Consumer Cyclical              Restaurants               6,500  Domino's Pizza, Inc., through its subsidiaries...                  29.2                    10.6                    6.3               12.2  Moderate Controversy Level                2.0     66th percentile         Medium
3    DAY            Dayforce, Inc.  3311 East Old Shakopee Road\nMinneapolis, MN 5...         Technology   Software - Application               9,084  Dayforce Inc., together with its subsidiaries,...                   NaN                     NaN                    NaN                NaN                         NaN                NaN                 NaN            NaN
4    DVA               Davita Inc.  2000 16th Street\nDenver, CO 80202\nUnited States         Healthcare  Medical Care Facilities              70,000  DaVita Inc. provides kidney dialysis services ...                  22.6                     0.1                    8.4               14.1  Moderate Controversy Level                2.0     38th percentile         Medium

#### Vendo a quantidade de linhas e features da tabela

In [7]:
df_esg.shape

(503, 15)

#### Verificando os tipos de dados

In [8]:
df_types_esg = pd.DataFrame(df_esg.dtypes, columns=['Tipo de Dado'])

In [9]:
from IPython.display import display

# Forçar exibição completa
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.expand_frame_repr', False)

# Mostrar como tabela do notebook
display(df_types_esg)

                       Tipo de Dado
Symbol                       object
Name                         object
Address                      object
Sector                       object
Industry                     object
Full Time Employees          object
Description                  object
Total ESG Risk score        float64
Environment Risk Score      float64
Governance Risk Score       float64
Social Risk Score           float64
Controversy Level            object
Controversy Score           float64
ESG Risk Percentile          object
ESG Risk Level               object

#### Mantendo no Dataframe apenas colunas que serão utilizadas posteriormente

In [10]:
import pandas as pd
import re

# Renomear as colunas de interesse
df_esg_renomeado = df_esg.rename(columns={
    "Symbol": "ticker",
    "Name": "enterprise_name",
    "Sector": "enterprise_sector",
    "Full Time Employees": "full_time_employees",
    "Total ESG Risk score": "total_esg_risk_score",
    "Environment Risk Score": "environment_risk_score",
    "Governance Risk Score": "governance_risk_score",
    "Social Risk Score": "social_risk_score",
    "Controversy Level": "controversy_level",
    "Controversy Score": "controversy_score",
    "ESG Risk Percentile": "esg_risk_percentile",
    "ESG Risk Level": "esg_risk_level"
})

# Manter apenas as colunas selecionadas
colunas_de_interesse = [
    "ticker", "esg_risk_level"
]

df_esg_final = df_esg_renomeado[colunas_de_interesse]

# Opcional: remover registros sem total_esg_risk_score
#df_renomeado = df_renomeado.dropna(subset=["total_esg_risk_score"])

# Extrair o número da coluna 'esg_risk_percentile' e converter para inteiro
#df_esg_renomeado['esg_risk_percent'] = df_esg_renomeado['esg_risk_percentile'].astype(str).str.extract(r"(\d+)").astype(float).astype('Int64')

# Remover a coluna original 'esg_risk_percentile'
#df_esg_final = df_esg_renomeado.drop(columns=['esg_risk_percentile'])

# Visualizar o resultado
print(df_esg_final.head())

  ticker esg_risk_level
0   ENPH            NaN
1    EMN         Medium
2    DPZ         Medium
3    DAY            NaN
4    DVA         Medium

#### Realizando Join das bases por meio do campo ticker

In [11]:
# Realizar o join (equivalente ao inner join do SQL/Spark)
df_joined = pd.merge(df_yf, df_esg_final, on='ticker', how='inner')

In [12]:
df_joined.head()

                      address1         city state    zip        country         phone                   website                 industry              industrykey             industrydisp             sector          sectorkey         sectordisp                                longbusinesssummary  fulltimeemployees                                    companyofficers  auditrisk  boardrisk  compensationrisk  shareholderrightsrisk  overallrisk  governanceepochdate  compensationasofepochdate executiveteam   maxage  pricehint  previousclose    open   daylow  dayhigh  regularmarketpreviousclose  regularmarketopen  regularmarketdaylow  regularmarketdayhigh  payoutratio   beta  trailingpe  forwardpe      volume  regularmarketvolume  averagevolume  averagevolume10days  averagedailyvolume10day     bid     ask  bidsize  asksize     marketcap  fiftytwoweeklow  fiftytwoweekhigh  pricetosalestrailing12months  fiftydayaverage  twohundreddayaverage  trailingannualdividendrate  trailingannualdividendyield currency tradeable  enterprisevalue  profitmargins  floatshares  sharesoutstanding  sharesshort  sharesshortpriormonth  sharesshortpreviousmonthdate  dateshortinterest  sharespercentsharesout  heldpercentinsiders  heldpercentinstitutions  shortratio  shortpercentoffloat  impliedsharesoutstanding  bookvalue  pricetobook  lastfiscalyearend  nextfiscalyearend  mostrecentquarter  netincometocommon  trailingeps  forwardeps  enterprisetorevenue  enterprisetoebitda  52weekchange  sandp52weekchange quotetype  currentprice  targethighprice  targetlowprice  targetmeanprice  targetmedianprice  recommendationmean recommendationkey  numberofanalystopinions     totalcash  totalcashpershare        ebitda     totaldebt  quickratio  currentratio  totalrevenue  debttoequity  revenuepershare  returnonassets  returnonequity  grossprofits  freecashflow  operatingcashflow  revenuegrowth  grossmargins  ebitdamargins  operatingmargins financialcurrency symbol language region typedisp         quotesourcename triggerable custompricealertconfidence marketstate                 shortname                  longname                                   corporateactions  postmarkettime  regularmarkettime exchange   messageboardid exchangetimezonename exchangetimezoneshortname  gmtoffsetmilliseconds     market esgpopulated  regularmarketchangepercent  regularmarketprice  postmarketchangepercent  postmarketprice  postmarketchange  regularmarketchange  earningstimestamp  earningstimestampstart  earningstimestampend  earningscalltimestampstart  earningscalltimestampend isearningsdateestimate  epstrailingtwelvemonths  epsforward  epscurrentyear  priceepscurrentyear  fiftydayaveragechange  fiftydayaveragechangepercent  twohundreddayaveragechange  twohundreddayaveragechangepercent  sourceinterval  exchangedatadelayedby averageanalystrating cryptotradeable hasprepostmarketdata  firsttradedatemilliseconds regularmarketdayrange fullexchangename  averagedailyvolume3month  fiftytwoweeklowchange  fiftytwoweeklowchangepercent fiftytwoweekrange  fiftytwoweekhighchange  fiftytwoweekhighchangepercent  fiftytwoweekchangepercent     displayname  trailingpegratio ticker           fax                                          irwebsite  dividendrate  dividendyield  exdividenddate  fiveyearavgdividendyield  earningsquarterlygrowth lastsplitfactor  lastsplitdate  lastdividendvalue  lastdividenddate  earningsgrowth  dividenddate                   prevname namechangedate address2 underlyingsymbol uuid ipoexpecteddate industrysymbol esg_risk_level
0        47281 Bayside Parkway      Fremont    CA  94538  United States  707 774 7000   https://www.enphase.com                    Solar                    solar                    Solar         Technology         technology         Technology  Enphase Energy, Inc., together with its subsid...             2781.0  [{'maxAge': 1, 'name': 'Mr. Badrinarayanan  Ko...        6.0        7.0               9.0                   10.0          9.0         1.746058e+09               1.735603e+09            []  86400.0        2.0         38.005   37.77   37.600    39.97                      38.005              37.77               37.600                 39.97       0.0000  1.801   36.366970  10.830601  10168324.0           10168324.0      5963127.0           11089990.0               11089990.0   39.54   41.33     11.0      1.0  5.201046e+09            37.59            141.63                      3.654657          52.4044              75.50230                        0.00                     0.000000      USD     False     4.968794e+09        0.10434  126957223.0        131207000.0   16789560.0             18320382.0                  1.743379e+09       1.745971e+09                  0.1280              0.03228                  0.93586        3.24               0.1755               131207000.0      6.180     6.414239       1.735603e+09       1.767139e+09       1.743379e+09        148484992.0         1.09        3.66                3.491              21.987     -0.693616           0.093625    EQUITY         39.64            125.0            33.0         57.66944               50.5             2.61538              hold                     36.0  1.466857e+09             11.180  2.259830e+08  1.234605e+09       1.496         1.895  1.423128e+09       152.289           10.608         0.03012         0.17132  5.243710e+08  3.584797e+08       5.129060e+08          0.352       0.36846        0.15879           0.09853               USD   ENPH    en-US     US   Equity  Nasdaq Real Time Price        True                       HIGH      CLOSED      Enphase Energy, Inc.      Enphase Energy, Inc.                                                 []    1.748045e+09       1.748030e+09      NGM   finmb_40485464     America/New_York                       EDT            -14400000.0  us_market        False                    4.302061               39.64                 0.277499         39.75000          0.110001             1.634998       1.745352e+09            1.753096e+09          1.753445e+09                1.745354e+09              1.745354e+09                   True                     1.09        3.66         2.44745            16.196450             -12.764401                     -0.243575                  -35.862297                          -0.474983            15.0                    0.0           2.6 - Hold           False                 True                1.333114e+12          37.6 - 39.97         NasdaqGM                 5963127.0               2.049999                      0.054536    37.59 - 141.63             -101.990005                      -0.720116                 -69.361565  Enphase Energy            0.4776   ENPH           NaN                                                NaN           NaN            NaN             NaN                       NaN                      NaN             NaN            NaN                NaN               NaN             NaN           NaN                        NaN            NaN      NaN              NaN  NaN             NaN            NaN            NaN
1       200 South Wilcox Drive    Kingsport    TN  37662  United States  423 229 2000   https://www.eastman.com      Specialty Chemicals      specialty-chemicals      Specialty Chemicals    Basic Materials    basic-materials    Basic Materials  Eastman Chemical Company operates as a special...            14000.0  [{'maxAge': 1, 'name': 'Mr. Mark J. Costa', 'a...        7.0        8.0               7.0                    6.0          7.0         1.746058e+09               1.735603e+09            []  86400.0        2.0         81.360   80.04   79.535    80.77                      81.360              80.04               79.535                 80.77       0.4178  1.304   10.259872   9.257472   1056459.0            1056459.0      1429998.0            1417400.0                1417400.0   79.98   81.08      8.0      9.0  9.299149e+09            70.90            114.50                      0.993287          81.5252              95.42480                        3.28                     0.040315      USD     False     1.406207e+10        0.09848  114438757.0        115460000.0    3198611.0              2944720.0                  1.743379e+09       1.745971e+09                  0.0277              0.00756                  0.93054        1.75               0.0321               115460000.0     50.871     1.583220       1.735603e+09       1.767139e+09       1.743379e+09        922000000.0         7.85        8.70                1.502               7.313     -0.200437           0.093625    EQUITY         80.54            118.0            76.0         96.62900               92.5             1.85000               buy                     20.0  4.180000e+08              3.622  1.923000e+09  5.112000e+09       0.739         1.719  9.362000e+09        86.003           80.603         0.05952         0.16032  2.332000e+09  5.323750e+08       1.136000e+09         -0.009       0.24909        0.20540           0.13930               USD    EMN    en-US     US   Equity  Nasdaq Real Time Price        True                       HIGH      CLOSED  Eastman Chemical Company  Eastman Chemical Company  [{'header': 'Dividend', 'message': 'EMN announ...    1.748039e+09       1.748030e+09      NYQ     finmb_109103     America/New_York                       EDT            -14400000.0  us_market        False                   -1.007870               80.54                 0.633228         81.05000          0.510002            -0.820000       1.745526e+09            1.753268e+09          1.753704e+09                1.745582e+09              1.745582e+09                   True                     7.85        8.70         7.41324            10.864346              -0.985199                     -0.012085                  -14.884796                          -0.155985            15.0                    0.0            1.9 - Buy           False                 True                7.558794e+11        79.535 - 80.77             NYSE                 1429998.0               9.639999                      0.135966      70.9 - 114.5              -33.960000                      -0.296594                 -20.043682             NaN            2.0155    EMN  423 229 2145  http://www.eastman.com/Company/Investors/Pages...          3.32           4.12    1.749773e+09                      3.22                    0.103             2:1   1.317686e+09               0.83      1.741910e+09           0.130  1.751933e+09                        NaN            NaN      NaN              NaN  NaN             NaN            NaN         Medium
2  30 Frank Lloyd Wright Drive    Ann Arbor    MI  48105  United States  734 930 3030    https://ir.dominos.com              Restaurants              restaurants              Restaurants  Consumer Cyclical  consumer-cyclical  Consumer Cyclical  Domino's Pizza, Inc. operates as a pizza compa...             6400.0  [{'maxAge': 1, 'name': 'Mr. David Allen Brando...        5.0        5.0               8.0                    8.0          7.0         1.746058e+09               1.735603e+09            []  86400.0        2.0        482.260  476.52  476.520   481.93                     482.260             476.52              476.520                481.93       0.3595  1.161   27.547590  27.235262    352287.0             352287.0       653724.0             451350.0                 451350.0  477.90  482.75      1.0      1.0  1.645064e+10           396.06            538.44                      3.475127         471.0510             446.03030                        6.27                     0.013001      USD     False     2.248561e+10        0.12844   33254603.0         34241500.0    1592194.0              1526648.0                  1.743379e+09       1.745971e+09                  0.0465              0.08071                  0.93183        2.22               0.0527                36813500.0   -112.880    -4.256113       1.735430e+09       1.766966e+09       1.631405e+09        607996992.0        17.44       17.64                4.750              24.048     -0.056278           0.093625    EQUITY        480.43            564.0           414.0        509.25820              530.0             1.90323               buy                     28.0  2.953520e+08              8.117  9.350310e+08  5.299668e+09       0.358         0.599  4.733825e+09           NaN          136.902         0.30322             NaN  1.346251e+09  4.742266e+08       6.805090e+08          0.031       0.28439        0.19752           0.18064               USD    DPZ    en-US     US   Equity  Nasdaq Real Time Price        True                       HIGH      CLOSED        Domino's Pizza Inc      Domino's Pizza, Inc.  [{'header': 'Dividend', 'message': 'DPZ announ...    1.748043e+09       1.748030e+09      NMS    finmb_3132512     America/New_York                       EDT            -14400000.0  us_market        False                   -0.379467              480.43                 0.054120        480.69000          0.260010            -1.830017       1.745835e+09            1.752669e+09          1.753101e+09                1.745843e+09              1.745843e+09                   True                    17.44       17.64        17.75041            27.065853               9.378998                      0.019911                   34.399690                           0.077124            15.0                    0.0            1.9 - Buy           False                 True                1.089725e+12       476.52 - 481.93         NasdaqGS                  653724.0              84.369995                      0.213023   396.06 - 538.44              -58.010010                      -0.107737                  -5.627799  Domino's Pizza            2.8275    DPZ           NaN                                                NaN          6.96           1.45    1.749773e+09                      1.06                    0.215             NaN            NaN               1.74      1.741910e+09           0.301  1.751242e+09                        NaN            NaN      NaN              NaN  NaN             NaN            NaN         Medium
3  3311 East Old Shakopee Road  Minneapolis    MN  55425  United States  952 853 8100  https://www.dayforce.com   Software - Application     software-application   Software - Application         Technology         technology         Technology  Dayforce Inc., together with its subsidiaries,...             9600.0  [{'maxAge': 1, 'name': 'Mr. David D. Ossip', '...        8.0       10.0               8.0                    7.0          9.0         1.746058e+09               1.735603e+09            []  86400.0        2.0         58.350   56.90   56.885    57.73                      58.350              56.90               56.885                 57.73       0.0000  1.172  357.687500  25.895927   1059142.0            1059142.0      2043320.0            1493670.0                1493670.0   57.40   70.00     10.0      8.0  9.149989e+09            47.08             82.69                      5.054405          57.0718              64.09455                        0.00                     0.000000      USD     False     9.823894e+09        0.01431  156677052.0        159880992.0    7606815.0              7482389.0                  1.743379e+09       1.745971e+09                  0.0476              0.01234                  1.09411        4.35               0.0869               159880992.0     16.201     3.532498       1.735603e+09       1.767139e+09       1.743379e+09         25900000.0         0.16        2.21                5.427              42.072      0.056294           0.093625    EQUITY         57.23             95.0            55.0         68.37294               68.0             1.94737               buy                     17.0  5.573000e+08              3.486  2.335000e+08  1.231200e+09       0.137         1.021  1.810300e+09        47.498           11.427         0.00551         0.01031  9.114000e+08  2.678125e+08       3.216000e+08          0.117       0.50345        0.12898           0.05438               USD    DAY    en-US     US   Equity           Delayed Quote        True                       HIGH      CLOSED            Dayforce, Inc.              Dayforce Inc                                                 []    1.748036e+09       1.748030e+09      NYQ  finmb_246737890     America/New_York                       EDT            -14400000.0  us_market        False                   -1.919450               57.23                -0.003159         57.22819         -0.001808            -1.120000       1.746616e+09            1.753792e+09          1.754311e+09                1.746619e+09              1.746619e+09                   True                     0.16        2.21         2.27933            25.108255               0.158199                      0.002772                   -6.864552                          -0.107100            15.0                    0.0            1.9 - Buy           False                 True                1.524749e+12        56.885 - 57.73             NYSE                 2043320.0              10.149998                      0.215590     47.08 - 82.69              -25.460003                      -0.307897                   5.629384        Dayforce               NaN    DAY           NaN                                                NaN           NaN            NaN             NaN                       NaN                    1.099             NaN            NaN                NaN               NaN           1.250           NaN  Ceridian HCM Holding Inc.     2025-05-24      NaN              NaN  NaN             NaN            NaN            NaN

#### Vendo a quantidade de linhas e features da nova tabela gerada após o cruzamento

In [13]:
df_joined.shape

(503, 190)

#### Assim, temos categorias numéricas e categóricas. Para as numéricas, vamos utilizar a função describe pra calcular as principais estatísticas, como mínimo, máximo, média, etc. Já para os dados categóricos, vamos calcular sua cardinalidade.

In [14]:
df_joined.describe()

       fulltimeemployees   auditrisk   boardrisk  compensationrisk  shareholderrightsrisk  overallrisk  governanceepochdate  compensationasofepochdate   maxage  pricehint  previousclose         open       daylow      dayhigh  regularmarketpreviousclose  regularmarketopen  regularmarketdaylow  regularmarketdayhigh  payoutratio        beta   trailingpe   forwardpe        volume  regularmarketvolume  averagevolume  averagevolume10days  averagedailyvolume10day          bid          ask     bidsize     asksize     marketcap  fiftytwoweeklow  fiftytwoweekhigh  pricetosalestrailing12months  fiftydayaverage  twohundreddayaverage  trailingannualdividendrate  trailingannualdividendyield  enterprisevalue  profitmargins   floatshares  sharesoutstanding   sharesshort  sharesshortpriormonth  sharesshortpreviousmonthdate  dateshortinterest  sharespercentsharesout  heldpercentinsiders  heldpercentinstitutions  shortratio  shortpercentoffloat  impliedsharesoutstanding      bookvalue  pricetobook  lastfiscalyearend  nextfiscalyearend  mostrecentquarter  netincometocommon  trailingeps  forwardeps  enterprisetorevenue  enterprisetoebitda  52weekchange  sandp52weekchange  currentprice  targethighprice  targetlowprice  targetmeanprice  targetmedianprice  recommendationmean  numberofanalystopinions     totalcash  totalcashpershare        ebitda     totaldebt  quickratio  currentratio  totalrevenue  debttoequity  revenuepershare  returnonassets  returnonequity  grossprofits  freecashflow  operatingcashflow  revenuegrowth  grossmargins  ebitdamargins  operatingmargins  postmarkettime  regularmarkettime  gmtoffsetmilliseconds  regularmarketchangepercent  regularmarketprice  postmarketchangepercent  postmarketprice  postmarketchange  regularmarketchange  earningstimestamp  earningstimestampstart  earningstimestampend  earningscalltimestampstart  earningscalltimestampend  epstrailingtwelvemonths  epsforward  epscurrentyear  priceepscurrentyear  fiftydayaveragechange  fiftydayaveragechangepercent  twohundreddayaveragechange  twohundreddayaveragechangepercent  sourceinterval  exchangedatadelayedby  firsttradedatemilliseconds  averagedailyvolume3month  fiftytwoweeklowchange  fiftytwoweeklowchangepercent  fiftytwoweekhighchange  fiftytwoweekhighchangepercent  fiftytwoweekchangepercent  trailingpegratio  dividendrate  dividendyield  exdividenddate  fiveyearavgdividendyield  earningsquarterlygrowth  lastsplitdate  lastdividendvalue  lastdividenddate  earningsgrowth  dividenddate
count       4.950000e+02  496.000000  496.000000        496.000000             496.000000   496.000000         4.960000e+02               4.980000e+02    501.0      500.0     499.000000   499.000000   499.000000   499.000000                  499.000000         499.000000           499.000000            499.000000   499.000000  496.000000   473.000000  499.000000  4.990000e+02         4.990000e+02   4.990000e+02         4.990000e+02             4.990000e+02   499.000000   499.000000  499.000000  499.000000  4.990000e+02       499.000000        499.000000                    499.000000       499.000000            499.000000                  499.000000                   499.000000     4.950000e+02     499.000000  4.990000e+02       4.990000e+02  4.990000e+02           4.990000e+02                  4.990000e+02       4.990000e+02              499.000000           499.000000               499.000000  499.000000           497.000000              4.990000e+02     499.000000   499.000000       4.990000e+02       4.990000e+02       4.990000e+02       4.990000e+02   499.000000  498.000000           495.000000          468.000000    499.000000       4.990000e+02    499.000000        497.00000      497.000000       497.000000         497.000000          489.000000               497.000000  4.950000e+02         495.000000  4.710000e+02  4.950000e+02  480.000000    480.000000  4.990000e+02    442.000000       499.000000      499.000000      469.000000  4.990000e+02  4.730000e+02       4.990000e+02     498.000000    499.000000     499.000000        499.000000    4.980000e+02       5.000000e+02                  500.0                  499.000000          499.000000               498.000000       498.000000        498.000000           499.000000       4.980000e+02            5.000000e+02          5.000000e+02                4.900000e+02              4.900000e+02               499.000000  498.000000      496.000000           496.000000             499.000000                    499.000000                  499.000000                         499.000000           500.0                  500.0                4.990000e+02              4.990000e+02             499.000000                    499.000000              499.000000                     499.000000                 499.000000        412.000000    406.000000     406.000000    4.260000e+02                395.000000               439.000000   3.680000e+02         427.000000      4.270000e+02      437.000000  4.190000e+02
mean        5.832195e+04    5.381048    5.366935          5.429435               5.312500     5.350806         1.746058e+09               1.730279e+09  86400.0        2.0     213.707786   211.654566   210.586960   214.297915                  213.707786         211.654566           210.587191            214.297785     0.736728    1.003810    35.954464   22.443784  4.945060e+06         4.945059e+06   6.904254e+06         6.052758e+06             6.052758e+06   205.747154   218.305451   11.212425   10.466934  1.068104e+11       164.831732        257.949458                      4.147946       207.021001            214.758617                    2.338407                     0.019474     1.119477e+11       0.133690  7.172839e+08       7.404985e+08  1.520686e+07           1.475373e+07                  1.742958e+09       1.745550e+09                0.029090             0.034939                 0.872883    2.549279             0.036365              7.704266e+08     952.314048     7.085781       1.733526e+09       1.765062e+09       1.741298e+09       4.108221e+09     8.116052   10.826165             4.751081           18.228902      0.059135       9.362543e-02    212.962347        282.21833      184.531066       235.235361         236.755040            2.155429                20.424547  1.692673e+10         513.303360  7.307377e+09  2.533649e+10    1.095767      1.615925  3.500876e+10    143.139624       609.384216        0.067172        0.303430  1.359281e+10  3.298285e+09       5.321250e+09       0.054221      0.445007       0.257688          0.182261    1.748042e+09       1.747657e+09            -14400000.0                   -0.388924          212.962347                 0.049083       212.957961         -0.030333            -0.745440       1.746846e+09            1.752826e+09          1.753188e+09                1.746629e+09              1.746629e+09                 8.116052   10.826165        9.967012            22.563284               5.941346                      0.020271                   -1.796271                          -0.023466            15.0                    0.0                6.593873e+11              6.904254e+06              48.130615                      0.288354              -44.987110                      -0.189428                   5.913489          3.274436      3.012537       2.466034    1.730086e+09                  2.372051                 0.249626   1.227400e+09           0.929227      1.723132e+09        0.226513  1.743661e+09
std         1.403950e+05    2.867083    2.852331          2.855981               2.876784     2.862844         0.000000e+00               3.552832e+07      0.0        0.0     465.539639   461.406734   461.096786   467.194062                  465.539639         461.406734           461.096886            467.194069     3.126043    0.388666   107.646485   29.147390  1.232663e+07         1.232663e+07   1.739489e+07         1.437473e+07             1.437473e+07   458.609052   484.602701   26.187058   24.257993  3.164118e+11       371.646769        573.874934                      3.940335       453.294344            481.284511                    2.830219                     0.017768     3.117349e+11       0.151982  1.678213e+09       1.663550e+09  2.300897e+07           2.247955e+07                  9.418081e+06       9.414214e+06                0.023152             0.082883                 0.132284    1.112707             0.032585              1.793494e+09   20363.046055    38.682270       8.139945e+06       8.139945e+06       1.444119e+07       1.194687e+10    24.889976   26.919825             4.145684           25.915356      0.287527       1.389171e-17    464.592730        564.00016      423.368773       498.294348         508.038366            0.421602                 8.170489  1.045309e+11       10865.713287  1.693775e+10  8.254561e+10    1.490978      1.531812  7.141051e+10    311.825182     11561.498788        0.057099        0.994577  2.892428e+10  8.554413e+09       1.610372e+10       0.126935      0.235571       0.180876          0.463808    3.695242e+03       8.330271e+06                    0.0                    1.568785          464.592730                 0.828031       465.077142          1.986447             4.140098       2.531297e+06            9.849012e+06          9.850980e+06                2.544537e+06              2.544537e+06                24.889976   26.919825       22.905156            18.801664              32.900214                      0.073691                   75.553959                           0.135492             0.0                    0.0                4.712265e+11              1.739489e+07             123.731196                      0.232588              141.660967                       0.136417                  28.752721          8.999399      3.021764       1.690096    1.095308e+08                  1.410105                 1.526038   3.061496e+08           3.682160      1.198630e+08        1.342495  4.354060e+07
min         2.700000e+01    1.000000    1.000000          1.000000               1.000000     1.000000         1.746058e+09               1.451520e+09  86400.0        2.0       8.380000     8.260000     8.190000     8.310000                    8.380000           8.260000             8.190000              8.310000     0.000000    0.046000     5.429348  -69.230774  1.861300e+04         1.861300e+04   2.355000e+04         1.748000e+04             1.748000e+04     0.000000     0.000000    1.000000    1.000000  4.629051e+09         6.640000         11.480000                      0.063569         8.431600              9.233900                    0.000000                     0.000000    -2.187589e+11      -1.056660  1.225341e+06       2.923830e+06  9.291000e+04           8.443400e+04                  1.532995e+09       1.535674e+09                0.003300             0.000180                 0.360550    0.580000             0.006000              8.000000e+03    -266.183000  -127.243040       1.625011e+09       1.656547e+09       1.621642e+09      -1.919600e+10   -76.530000   -8.700000            -3.392000          -24.039000     -0.828590       9.362543e-02      8.290000         13.00000        7.000000        10.311300          10.000000            1.307690                 1.000000  2.908000e+06           0.009000 -7.688000e+09  0.000000e+00    0.004000      0.036000  8.153550e+08      0.543000         3.074000       -0.158370       -1.632120 -2.617000e+09 -1.639450e+10      -1.396930e+11      -0.427000     -0.823730      -1.113310         -9.722219    1.748031e+09       1.561760e+09            -14400000.0                  -19.858800            8.290000                -4.747129         8.270000        -31.091797           -32.790000       1.741266e+09            1.535458e+09          1.536077e+09                1.730381e+09              1.730381e+09               -76.530000   -8.700000       -9.981830          -114.391670            -228.821170                     -0.343659                -1218.608900                          -0.474983            15.0                    0.0               -2.523222e+11              2.355000e+04               0.200001                      0.006828            -2898.379400                      -0.840583                 -82.859010          0.115500      0.040000       0.030000    6.337440e+08                  0.020000                -0.985000  -2.262816e+08           0.000000      6.337440e+08       -0.985000  1.201046e+09
25%         1.040000e+04    3.000000    3.000000          3.000000               3.000000     3.000000         1.746058e+09               1.735603e+09  86400.0        2.0      64.465000    63.935500    63.595000    64.522500                   64.465000          63.935500            63.595000             64.522500     0.133350    0.738000    16.336447   11.974944  9.778225e+05         9.778225e+05   1.527322e+06         1.288395e+06             1.288395e+06    61.580000    66.090000    8.000000    8.000000  1.789645e+10        50.080000         82.590000                      1.493292        63.681100             67.156000                    0.530000                     0.005168     2.240771e+10       0.068440  1.477710e+08       1.546665e+08  3.805184e+06           3.647936e+06                  1.743379e+09       1.745971e+09                0.014950             0.002225                 0.806100    1.770000             0.017000              1.497825e+08      13.342000     1.647695       1.735603e+09       1.767139e+09       1.743379e+09       6.964000e+08     2.405000    3.690000             1.904500           10.647500     -0.133585       9.362543e-02     64.182500         88.59000       55.430000        72.708150          72.000000            1.850000                15.000000  5.221500e+08           1.934000  1.679979e+09  3.656650e+09    0.503750      0.872500  6.511500e+09     40.806500        21.669000        0.031245        0.088940  2.842332e+09  5.796625e+08       1.173782e+09      -0.010750      0.289150       0.145260          0.106215    1.748040e+09       1.748030e+09            -14400000.0                   -0.948177           64.182500                -0.194583        63.911250         -0.310009            -1.425010       1.745505e+09            1.753101e+09          1.753447e+09                1.745505e+09              1.745505e+09                 2.405000    3.690000        3.525065            13.241433              -1.739202                     -0.021947                  -12.443351                          -0.102796            15.0                    0.0                3.221514e+11              1.527322e+06               8.290000                      0.139821              -46.720086                      -0.274172                 -13.358522          1.215150      1.172500       1.162500    1.746144e+09                  1.235000                -0.186000   9.699048e+08           0.280000      1.741306e+09       -0.183000  1.747699e+09
50%         2.181700e+04    5.000000    5.000000          5.000000               5.000000     5.000000         1.746058e+09               1.735603e+09  86400.0        2.0     112.980000   111.330000   110.710000   113.155000                  112.980000         111.330000           110.710000            113.155000     0.350000    1.007500    23.942005   18.139923  1.993203e+06         1.993203e+06   2.944220e+06         2.717370e+06             2.717370e+06   107.290000   115.890000    8.000000    8.000000  3.443925e+10        90.990000        149.049500                      2.986963       114.792000            120.984500                    1.700000                     0.015750     4.266228e+10       0.123330  2.960038e+08       3.071810e+08  7.526161e+06           7.241921e+06                  1.743379e+09       1.745971e+09                0.022700             0.004640                 0.894540    2.260000             0.027200              3.092710e+08      28.820000     3.062005       1.735603e+09       1.767139e+09       1.743379e+09       1.449700e+09     5.130000    6.900000             3.491000           14.741000      0.055949       9.362543e-02    112.640000        163.00000      100.000000       133.441500         130.000000            2.105260                20.000000  1.583935e+09           4.790000  2.952221e+09  8.392783e+09    0.793500      1.245000  1.346200e+10     75.440000        39.890000        0.054480        0.152140  5.634000e+09  1.286625e+09       2.412000e+09       0.044500      0.436080       0.235700          0.181340    1.748044e+09       1.748030e+09            -14400000.0                   -0.358476          112.640000                 0.000000       112.340000          0.000000            -0.279999       1.746095e+09            1.753700e+09          1.754050e+09                1.746103e+09              1.746103e+09                 5.130000    6.900000        6.188985            19.020439               1.388794                      0.013968                   -1.830549                          -0.021168            15.0                    0.0                6.775110e+11              2.944220e+06              21.906670                      0.237705              -21.650002                      -0.161895                   5.594933          1.970400      2.320000       2.155000    1.747958e+09                  2.260000                 0.048000   1.181002e+09           0.568000      1.743379e+09        0.063000  1.749686e+09
75%         5.565000e+04    8.000000    8.000000          8.000000               8.000000     8.000000         1.746058e+09               1.735603e+09  86400.0        2.0     228.445000   227.975000   227.037100   230.835000                  228.445000         227.975000           227.037100            230.835000     0.621800    1.268250    34.173410   25.429087  4.463334e+06         4.463334e+06   5.970680e+06         5.600715e+06             5.600715e+06   220.300000   238.730000   11.000000   10.000000  8.058117e+10       171.305000        269.140000                      5.492200       224.654000            225.044900                    3.275000                     0.030248     9.546053e+10       0.198380  6.502860e+08       6.793330e+08  1.739160e+07           1.710586e+07                  1.743379e+09       1.745971e+09                0.034500             0.018120                 0.967540    3.040000             0.043700              6.757025e+08      53.871500     6.551645       1.735603e+09       1.767139e+09       1.743379e+09       3.422895e+09     8.800000   11.262500             6.211000           19.967750      0.228905       9.362543e-02    229.425000        300.00000      195.000000       248.492400         250.000000            2.428570                24.000000  4.753250e+09          11.676500  6.185406e+09  1.968750e+10    1.204250      1.826250  2.825766e+10    147.803250        81.049000        0.086900        0.284210  1.153700e+10  3.021000e+09       5.048751e+09       0.102750      0.604000       0.354785          0.278255    1.748045e+09       1.748030e+09            -14400000.0                    0.309706          229.425000                 0.220380       229.147500          0.209999             0.260003       1.746649e+09            1.753879e+09          1.754311e+09                1.746629e+09              1.746629e+09                 8.800000   11.262500       10.879227            26.970419               7.756500                      0.060041                    6.659126                           0.056732            15.0                    0.0                1.000301e+12              5.970680e+06              47.640003                      0.371570               -9.270000                      -0.080587                  22.890544          2.822550      3.960000       3.415000    1.749427e+09                  3.250000                 0.238000   1.465970e+09           0.990000      1.746706e+09        0.262000  1.751242e+09

#### Como podemos ver na primeira linha da tabela acima, nem todos as features têm a mesma quantidade de dados, isto é, temos uma certa quantidade de dados nulos. Vamos calcular em porcentagem quanto cada coluna possui.

In [15]:
df_joined.isnull().sum().div(len(df_joined)).sort_values(ascending = False)

industrysymbol                       0.998012
underlyingsymbol                     0.996024
uuid                                 0.996024
ipoexpecteddate                      0.978131
namechangedate                       0.920477
prevname                             0.920477
fax                                  0.838966
address2                             0.743539
irwebsite                            0.316103
lastsplitdate                        0.268390
lastsplitfactor                      0.268390
fiveyearavgdividendyield             0.214712
dividendrate                         0.192843
dividendyield                        0.192843
displayname                          0.190855
trailingpegratio                     0.180915
dividenddate                         0.166998
exdividenddate                       0.153082
lastdividenddate                     0.151093
lastdividendvalue                    0.151093
esg_risk_level                       0.145129
earningsgrowth                       0.131213
earningsquarterlygrowth              0.127237
debttoequity                         0.121272
enterprisetoebitda                   0.069583
returnonequity                       0.067594
ebitda                               0.063618
freecashflow                         0.059642
trailingpe                           0.059642
quotesourcename                      0.057654
currentratio                         0.045726
quickratio                           0.045726
state                                0.045726
recommendationmean                   0.027833
averageanalystrating                 0.027833
earningscalltimestampstart           0.025845
earningscalltimestampend             0.025845
enterprisevalue                      0.015905
totaldebt                            0.015905
enterprisetorevenue                  0.015905
totalcashpershare                    0.015905
totalcash                            0.015905
fulltimeemployees                    0.015905
shareholderrightsrisk                0.013917
compensationrisk                     0.013917
boardrisk                            0.013917
priceepscurrentyear                  0.013917
governanceepochdate                  0.013917
auditrisk                            0.013917
overallrisk                          0.013917
beta                                 0.013917
epscurrentyear                       0.013917
numberofanalystopinions              0.011928
targetmeanprice                      0.011928
targethighprice                      0.011928
targetlowprice                       0.011928
shortpercentoffloat                  0.011928
targetmedianprice                    0.011928
zip                                  0.011928
phone                                0.011928
epsforward                           0.009940
compensationasofepochdate            0.009940
postmarketprice                      0.009940
postmarketchangepercent              0.009940
postmarketchange                     0.009940
forwardeps                           0.009940
revenuegrowth                        0.009940
postmarkettime                       0.009940
earningstimestamp                    0.009940
sharesoutstanding                    0.007952
fiftytwoweekhigh                     0.007952
twohundreddayaverage                 0.007952
fiftydayaverage                      0.007952
pricetosalestrailing12months         0.007952
marketcap                            0.007952
fiftytwoweeklow                      0.007952
trailingannualdividendyield          0.007952
trailingannualdividendrate           0.007952
sharesshortpreviousmonthdate         0.007952
regularmarketprice                   0.007952
regularmarketchangepercent           0.007952
sharesshort                          0.007952
profitmargins                        0.007952
currency                             0.007952
floatshares                          0.007952
volume                               0.007952
regularmarketopen                    0.007952
payoutratio                          0.007952
regularmarketdaylow                  0.007952
regularmarketdayhigh                 0.007952
regularmarketpreviousclose           0.007952
dayhigh                              0.007952
asksize                              0.007952
bidsize                              0.007952
country                              0.007952
city                                 0.007952
address1                             0.007952
daylow                               0.007952
previousclose                        0.007952
open                                 0.007952
executiveteam                        0.007952
companyofficers                      0.007952
website                              0.007952
industry                             0.007952
industrykey                          0.007952
industrydisp                         0.007952
sector                               0.007952
sectorkey                            0.007952
sectordisp                           0.007952
longbusinesssummary                  0.007952
forwardpe                            0.007952
ask                                  0.007952
bid                                  0.007952
averagedailyvolume10day              0.007952
averagevolume10days                  0.007952
averagevolume                        0.007952
regularmarketvolume                  0.007952
lastfiscalyearend                    0.007952
trailingeps                          0.007952
netincometocommon                    0.007952
mostrecentquarter                    0.007952
nextfiscalyearend                    0.007952
sharespercentsharesout               0.007952
sharesshortpriormonth                0.007952
dateshortinterest                    0.007952
pricetobook                          0.007952
fiftytwoweekchangepercent            0.007952
fiftytwoweekrange                    0.007952
fiftytwoweeklowchange                0.007952
regularmarketchange                  0.007952
isearningsdateestimate               0.007952
fiftydayaveragechange                0.007952
fiftydayaveragechangepercent         0.007952
averagedailyvolume3month             0.007952
fiftytwoweekhighchangepercent        0.007952
fiftytwoweekhighchange               0.007952
fiftytwoweeklowchangepercent         0.007952
epstrailingtwelvemonths              0.007952
financialcurrency                    0.007952
shortname                            0.007952
ebitdamargins                        0.007952
longname                             0.007952
grossprofits                         0.007952
totalrevenue                         0.007952
grossmargins                         0.007952
operatingcashflow                    0.007952
revenuepershare                      0.007952
returnonassets                       0.007952
bookvalue                            0.007952
impliedsharesoutstanding             0.007952
shortratio                           0.007952
heldpercentinstitutions              0.007952
heldpercentinsiders                  0.007952
52weekchange                         0.007952
sandp52weekchange                    0.007952
currentprice                         0.007952
recommendationkey                    0.007952
operatingmargins                     0.007952
regularmarketdayrange                0.007952
firsttradedatemilliseconds           0.007952
twohundreddayaveragechangepercent    0.007952
twohundreddayaveragechange           0.007952
earningstimestampend                 0.005964
exchangetimezoneshortname            0.005964
pricehint                            0.005964
market                               0.005964
exchange                             0.005964
typedisp                             0.005964
marketstate                          0.005964
messageboardid                       0.005964
gmtoffsetmilliseconds                0.005964
exchangetimezonename                 0.005964
earningstimestampstart               0.005964
regularmarkettime                    0.005964
exchangedatadelayedby                0.005964
sourceinterval                       0.005964
fullexchangename                     0.005964
maxage                               0.003976
tradeable                            0.003976
triggerable                          0.003976
region                               0.003976
language                             0.003976
cryptotradeable                      0.003976
hasprepostmarketdata                 0.003976
custompricealertconfidence           0.003976
corporateactions                     0.003976
esgpopulated                         0.003976
quotetype                            0.000000
symbol                               0.000000
ticker                               0.000000
dtype: float64

#### Dropando colunas com muitos dados nulos, ou com entropia 0, irrelevantes para o modelo ou que podem induzir o modelo a uma determinada classificação

In [16]:
# Calcula a porcentagem de valores nulos por coluna
porcentagem_nulos = df_joined.isnull().sum().div(len(df_joined))

# Filtra colunas com menos de 30% de nulos
colunas_validas = porcentagem_nulos[porcentagem_nulos < 0.3].index

# Mantém apenas as colunas com menos de 30% de nulos
df_filtrado = df_joined[colunas_validas]

# Dropando colunas com muitos dados nulos e que não são relevantes para o modelo
#Obs: O campo companyofficers pode ser útil mas seu tratamento requer tratamentos mais avançados que podem ser feitos no futuro
colunas_para_dropar = [
        'lastsplitfactor',
        'lastsplitdate',
        'displayname',
        'dividenddate',
        'exdividenddate',
        'lastdividenddate',
        'earningscalltimestampend',
        'earningscalltimestampstart',
        'governanceepochdate',
        'zip',
        'phone',
        'compensationasofepochdate',
        'earningstimestamp',
        'corporateactions',
        'address1',
        'city',
        'website',
        'industry',
        'industrydisp',
        'sector',
        'sectordisp',
        'longbusinesssummary',
        'currency',
        'quotetype',
        'financialcurrency',
        'financialcurrency',
        'symbol',
        'language',
        'region',
        'typedisp',
        'quotesourcename',
        'messageboardid',
        'exchangetimezonename',
        'exchangetimezoneshortname',
        'market',
        'marketstate',
        'shortname',
        'longname',
        'averageanalystrating',
        'postmarkettime',
        'companyofficers',
        'executiveteam',
        'custompricealertconfidence',
        'tradeable',
        'triggerable',
        'esgpopulated',
        'cryptotradeable',
        'hasprepostmarketdata',
        'fullexchangename',
        'isearningsdateestimate',
        'state', 
        'country', 
        'industrykey',
        'sectorkey', 
        'recommendationkey', 
        'exchange',
        'pricehint',
        'maxage',
        'gmtoffsetmilliseconds',
        'sandp52weekchange',
        'sourceinterval',
        'exchangedatadelayedby',
        'dateshortinterest',
        'regularmarkettime',
        'sharesshortpreviousmonthdate',
        'open',
        'regularmarketpreviousclose',
        'firsttradedatemilliseconds',
        'earningstimestampstart',
    	'earningstimestampend',
    	'targethighprice',
    	'mostrecentquarter',
    	'targetlowprice',
    	'fiftytwoweekrange_min',
    	'regularmarketdayrange_min',
    	'ask',
    	'currentprice',
    	'daylow',
    	'fiftydayaverage',
    	'postmarketprice',
    	'dayhigh',
    	'targetmeanprice',
    	'previousclose',
    	'regularmarketprice',
    	'regularmarketopen',
        'regularmarketdaylow',
    	'regularmarketdayhigh']
    
df = df_filtrado.drop(columns=colunas_para_dropar, errors='ignore')

In [17]:
df.shape

(503, 97)

#### Deletando os 4 tickers pois estão quase sem quaisquer informações

In [18]:
# Lista dos tickers a serem removidos
tickers_para_remover = ['WRK', 'MRO', 'CTLT', 'BF.B']

# Remove as linhas cujo Ticker está na lista
df = df[~df['ticker'].isin(tickers_para_remover)]

In [19]:
df.shape

(499, 97)

#### Preenchendo valores nulos com 0 nas colunas indicadas

In [20]:
# Lista das colunas a preencher
colunas_para_preencher = [
    'fiveyearavgdividendyield',
    'dividendrate',
    'dividendyield',
    'lastdividendvalue'
]

# Preenche os valores nulos com 0 nessas colunas
df.loc[:, colunas_para_preencher] = df[colunas_para_preencher].fillna(0)

#### Preenchendo valores nulos com média e moda

In [21]:
import pandas as pd

# Dicionário com as colunas e o método de preenchimento
colunas_preenchimento = {
    'trailingpegratio': 'media',
    'earningsgrowth': 'media',
    'earningsquarterlygrowth': 'media',
    'debttoequity': 'media',
    'enterprisetoebitda': 'media',
    'returnonequity': 'media',
    'ebitda': 'media',
    'freecashflow': 'media',
    'trailingpe': 'media',
    'quickratio': 'media',
    'currentratio': 'media',
    'recommendationmean': 'media',
    'enterprisetorevenue': 'media',
    'enterprisevalue': 'media',
    'totaldebt': 'media',
    'totalcashpershare': 'media',
    'totalcash': 'media',
    'overallrisk': 'media',
    'priceepscurrentyear': 'media',
    'epscurrentyear': 'media',
    'beta': 'media',
    'auditrisk': 'moda',
    'compensationrisk': 'moda',
    'shareholderrightsrisk': 'moda',
    'boardrisk': 'moda',
    'shortpercentoffloat': 'media',
    'numberofanalystopinions': 'moda',
    'revenuegrowth': 'media',
    'operatingcashflow': 'media',
    'epsforward': 'media',
    'forwardeps': 'media',
    'targetmedianprice': 'media',
    'fulltimeemployees': 'media',
    'postmarketchangepercent': 'media',
    'postmarketchange': 'media'
    
}

# Aplica o preenchimento apropriado
for coluna, metodo in colunas_preenchimento.items():
    if metodo == 'media':
        valor = pd.to_numeric(df[coluna], errors='coerce').mean(skipna=True)
    elif metodo == 'moda':
        valor = df[coluna].mode(dropna=True)
        valor = valor.iloc[0] if not valor.empty else None
    else:
        continue  # ignora métodos não reconhecidos

    # Preenche os valores nulos com o valor calculado
    df[coluna] = df[coluna].fillna(valor)

#### Agora não temos mais valores nulos em nossas features apenas no nosso target

In [22]:
df.isnull().sum().div(len(df_joined)).sort_values(ascending = False)

esg_risk_level                       0.139165
auditrisk                            0.000000
boardrisk                            0.000000
compensationrisk                     0.000000
shareholderrightsrisk                0.000000
overallrisk                          0.000000
payoutratio                          0.000000
beta                                 0.000000
trailingpe                           0.000000
forwardpe                            0.000000
volume                               0.000000
regularmarketvolume                  0.000000
averagevolume                        0.000000
averagevolume10days                  0.000000
averagedailyvolume10day              0.000000
bid                                  0.000000
bidsize                              0.000000
asksize                              0.000000
marketcap                            0.000000
fiftytwoweeklow                      0.000000
fiftytwoweekhigh                     0.000000
pricetosalestrailing12months         0.000000
twohundreddayaverage                 0.000000
trailingannualdividendrate           0.000000
trailingannualdividendyield          0.000000
enterprisevalue                      0.000000
profitmargins                        0.000000
floatshares                          0.000000
sharesoutstanding                    0.000000
sharesshort                          0.000000
sharesshortpriormonth                0.000000
sharespercentsharesout               0.000000
fulltimeemployees                    0.000000
heldpercentinsiders                  0.000000
heldpercentinstitutions              0.000000
shortpercentoffloat                  0.000000
shortratio                           0.000000
bookvalue                            0.000000
pricetobook                          0.000000
lastfiscalyearend                    0.000000
impliedsharesoutstanding             0.000000
netincometocommon                    0.000000
trailingeps                          0.000000
forwardeps                           0.000000
enterprisetorevenue                  0.000000
enterprisetoebitda                   0.000000
52weekchange                         0.000000
targetmedianprice                    0.000000
nextfiscalyearend                    0.000000
numberofanalystopinions              0.000000
totalcash                            0.000000
totalcashpershare                    0.000000
ebitda                               0.000000
totaldebt                            0.000000
quickratio                           0.000000
currentratio                         0.000000
totalrevenue                         0.000000
debttoequity                         0.000000
revenuepershare                      0.000000
returnonassets                       0.000000
returnonequity                       0.000000
grossprofits                         0.000000
freecashflow                         0.000000
operatingcashflow                    0.000000
recommendationmean                   0.000000
revenuegrowth                        0.000000
grossmargins                         0.000000
operatingmargins                     0.000000
ebitdamargins                        0.000000
postmarketchangepercent              0.000000
postmarketchange                     0.000000
regularmarketchange                  0.000000
regularmarketchangepercent           0.000000
epsforward                           0.000000
epscurrentyear                       0.000000
priceepscurrentyear                  0.000000
fiftydayaveragechange                0.000000
fiftydayaveragechangepercent         0.000000
twohundreddayaveragechange           0.000000
twohundreddayaveragechangepercent    0.000000
epstrailingtwelvemonths              0.000000
regularmarketdayrange                0.000000
averagedailyvolume3month             0.000000
fiftytwoweeklowchangepercent         0.000000
fiftytwoweeklowchange                0.000000
fiftytwoweekhighchange               0.000000
fiftytwoweekhighchangepercent        0.000000
fiftytwoweekchangepercent            0.000000
fiftytwoweekrange                    0.000000
trailingpegratio                     0.000000
ticker                               0.000000
dividendyield                        0.000000
dividendrate                         0.000000
fiveyearavgdividendyield             0.000000
earningsquarterlygrowth              0.000000
lastdividendvalue                    0.000000
earningsgrowth                       0.000000
dtype: float64

#### Tratando colunas com range de valores ('37.59 - 141.63')

In [23]:
# Trata regularmarketdayrange
df[['regularmarketdayrange_min', 'regularmarketdayrange_max']] = (
    df['regularmarketdayrange']
    .str.split(' - ', expand=True)
    .astype(float)
)

# Trata fiftytwoweekrange
df[['fiftytwoweekrange_min', 'fiftytwoweekrange_max']] = (
    df['fiftytwoweekrange']
    .str.split(' - ', expand=True)
    .astype(float)
)

# Dropando colunas originais
df = df.drop(columns=['regularmarketdayrange', 'fiftytwoweekrange'])

#### Analisando nosso target

##### Vendo a quantida de valores distintos existentes

In [24]:
df['esg_risk_level'].nunique()

5

##### Vendo quais são esses valores

In [25]:
df['esg_risk_level'].unique()

array([nan, 'Medium', 'Low', 'High', 'Severe', 'Negligible'], dtype=object)

##### Vendo a quantidade de cada valor distinto

In [26]:
df['esg_risk_level'].value_counts()

esg_risk_level
Low           187
Medium        184
High           49
Negligible      6
Severe          3
Name: count, dtype: int64

##### Transformando os clases de com pouca quantidade para melhor performance do modelo

In [27]:
df['esg_risk_level'] = df['esg_risk_level'].replace({
    'Negligible': 'Low',
    'Severe': 'High'
})

In [28]:
df['esg_risk_level'].value_counts()

esg_risk_level
Low       193
Medium    184
High       52
Name: count, dtype: int64

In [29]:
df['esg_risk_level'].unique()

array([nan, 'Medium', 'Low', 'High'], dtype=object)

#### Verificando a quantidade de nulos em nosso target

In [30]:
qtd_nulos = df['esg_risk_level'].isnull().sum()
print(f"Número de registros com esg_risk_level nulo: {qtd_nulos}")

Número de registros com esg_risk_level nulo: 70

### Salvando DF filtrado para possibilitar análise por setor

In [33]:
# Salvar CSV
df_salvar_f = pd.DataFrame(df_filtrado)
df_salvar_f.to_csv("base_filtrada.csv", index=False)
print("Arquivo salvo como base_filtrada.csv")

Arquivo salvo como base_filtrada.csv

### Lendo DF filtrado

In [1]:
import pandas as pd

# Caminho completo para o CSV
caminho_arquivo_filtrado = r'C:\Users\lucas\TG - ESG\Datasets\base_filtrada.csv'

# Ler o arquivo
df_filtrado = pd.read_csv(caminho_arquivo_filtrado)

df_filtrado.head()

,address1,city,state,zip,country,phone,website,industry,industrykey,industrydisp,...,exdividenddate,fiveyearavgdividendyield,earningsquarterlygrowth,lastsplitfactor,lastsplitdate,lastdividendvalue,lastdividenddate,earningsgrowth,dividenddate,esg_risk_level
0,47281 Bayside Parkway,Fremont,CA,94538,United States,707 774 7000,https://www.enphase.com,Solar,solar,Solar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,200 South Wilcox Drive,Kingsport,TN,37662,United States,423 229 2000,https://www.eastman.com,Specialty Chemicals,specialty-chemicals,Specialty Chemicals,...,1.749773e+09,3.22,0.103,2:1,1.317686e+09,0.83,1.741910e+09,0.130,1.751933e+09,Medium
2,30 Frank Lloyd Wright Drive,Ann Arbor,MI,48105,United States,734 930 3030,https://ir.dominos.com,Restaurants,restaurants,Restaurants,...,1.749773e+09,1.06,0.215,NaN,NaN,1.74,1.741910e+09,0.301,1.751242e+09,Medium
3,3311 East Old Shakopee Road,Minneapolis,MN,55425,United States,952 853 8100,https://www.dayforce.com,Software - Application,software-application,Software - Application,...,NaN,NaN,1.099,NaN,NaN,NaN,NaN,1.250,NaN,NaN
4,2000 16th Street,Denver,CO,80202,United States,720-631-2100,https://www.davita.com,Medical Care Facilities,medical-care-facilities,Medical Care Facilities,...,NaN,NaN,-0.320,2:1,1.378685e+09,NaN,NaN,-0.245,NaN,Medium

### Salvando DF tratado

In [31]:
# Salvar CSV
df_salvar = pd.DataFrame(df)
df_salvar.to_csv("base_tratada.csv", index=False)
print("Arquivo salvo como base_tratada.csv")

Arquivo salvo como base_tratada.csv

### Lendo DF tratado

In [32]:
import pandas as pd

# Caminho completo para o CSV
caminho_arquivo = r'C:\Users\lucas\TG - ESG\Datasets\base_tratada.csv'

# Ler o arquivo
df = pd.read_csv(caminho_arquivo)

df.head()

   fulltimeemployees  auditrisk  boardrisk  compensationrisk  shareholderrightsrisk  overallrisk  payoutratio   beta  trailingpe  forwardpe      volume  regularmarketvolume  averagevolume  averagevolume10days  averagedailyvolume10day     bid  bidsize  asksize     marketcap  fiftytwoweeklow  fiftytwoweekhigh  pricetosalestrailing12months  twohundreddayaverage  trailingannualdividendrate  trailingannualdividendyield  enterprisevalue  profitmargins  floatshares  sharesoutstanding  sharesshort  sharesshortpriormonth  sharespercentsharesout  heldpercentinsiders  heldpercentinstitutions  shortratio  shortpercentoffloat  impliedsharesoutstanding  bookvalue  pricetobook  lastfiscalyearend  nextfiscalyearend  netincometocommon  trailingeps  forwardeps  enterprisetorevenue  enterprisetoebitda  52weekchange  targetmedianprice  recommendationmean  numberofanalystopinions     totalcash  totalcashpershare        ebitda     totaldebt  quickratio  currentratio  totalrevenue  debttoequity  revenuepershare  returnonassets  returnonequity  grossprofits  freecashflow  operatingcashflow  revenuegrowth  grossmargins  ebitdamargins  operatingmargins  regularmarketchangepercent  postmarketchangepercent  postmarketchange  regularmarketchange  epstrailingtwelvemonths  epsforward  epscurrentyear  priceepscurrentyear  fiftydayaveragechange  fiftydayaveragechangepercent  twohundreddayaveragechange  twohundreddayaveragechangepercent  averagedailyvolume3month  fiftytwoweeklowchange  fiftytwoweeklowchangepercent  fiftytwoweekhighchange  fiftytwoweekhighchangepercent  fiftytwoweekchangepercent  trailingpegratio ticker  dividendrate  dividendyield  fiveyearavgdividendyield  earningsquarterlygrowth  lastdividendvalue  earningsgrowth esg_risk_level  regularmarketdayrange_min  regularmarketdayrange_max  fiftytwoweekrange_min  fiftytwoweekrange_max
0             2781.0        6.0        7.0               9.0                   10.0          9.0       0.0000  1.801   36.366970  10.830601  10168324.0           10168324.0      5963127.0           11089990.0               11089990.0   39.54     11.0      1.0  5.201046e+09            37.59            141.63                      3.654657              75.50230                        0.00                     0.000000     4.968794e+09        0.10434  126957223.0        131207000.0   16789560.0             18320382.0                  0.1280              0.03228                  0.93586        3.24               0.1755               131207000.0      6.180     6.414239       1.735603e+09       1.767139e+09        148484992.0         1.09        3.66                3.491              21.987     -0.693616               50.5             2.61538                     36.0  1.466857e+09             11.180  2.259830e+08  1.234605e+09       1.496         1.895  1.423128e+09    152.289000           10.608         0.03012         0.17132  5.243710e+08  3.584797e+08       5.129060e+08          0.352       0.36846        0.15879           0.09853                    4.302061                 0.277499          0.110001             1.634998                     1.09        3.66         2.44745            16.196450             -12.764401                     -0.243575                  -35.862297                          -0.474983                 5963127.0               2.049999                      0.054536             -101.990005                      -0.720116                 -69.361565          0.477600   ENPH          0.00           0.00                      0.00                 0.249626               0.00        0.226513            NaN                     37.600                      39.97                  37.59                 141.63
1            14000.0        7.0        8.0               7.0                    6.0          7.0       0.4178  1.304   10.259872   9.257472   1056459.0            1056459.0      1429998.0            1417400.0                1417400.0   79.98      8.0      9.0  9.299149e+09            70.90            114.50                      0.993287              95.42480                        3.28                     0.040315     1.406207e+10        0.09848  114438757.0        115460000.0    3198611.0              2944720.0                  0.0277              0.00756                  0.93054        1.75               0.0321               115460000.0     50.871     1.583220       1.735603e+09       1.767139e+09        922000000.0         7.85        8.70                1.502               7.313     -0.200437               92.5             1.85000                     20.0  4.180000e+08              3.622  1.923000e+09  5.112000e+09       0.739         1.719  9.362000e+09     86.003000           80.603         0.05952         0.16032  2.332000e+09  5.323750e+08       1.136000e+09         -0.009       0.24909        0.20540           0.13930                   -1.007870                 0.633228          0.510002            -0.820000                     7.85        8.70         7.41324            10.864346              -0.985199                     -0.012085                  -14.884796                          -0.155985                 1429998.0               9.639999                      0.135966              -33.960000                      -0.296594                 -20.043682          2.015500    EMN          3.32           4.12                      3.22                 0.103000               0.83        0.130000         Medium                     79.535                      80.77                  70.90                 114.50
2             6400.0        5.0        5.0               8.0                    8.0          7.0       0.3595  1.161   27.547590  27.235262    352287.0             352287.0       653724.0             451350.0                 451350.0  477.90      1.0      1.0  1.645064e+10           396.06            538.44                      3.475127             446.03030                        6.27                     0.013001     2.248561e+10        0.12844   33254603.0         34241500.0    1592194.0              1526648.0                  0.0465              0.08071                  0.93183        2.22               0.0527                36813500.0   -112.880    -4.256113       1.735430e+09       1.766966e+09        607996992.0        17.44       17.64                4.750              24.048     -0.056278              530.0             1.90323                     28.0  2.953520e+08              8.117  9.350310e+08  5.299668e+09       0.358         0.599  4.733825e+09    143.139624          136.902         0.30322         0.30343  1.346251e+09  4.742266e+08       6.805090e+08          0.031       0.28439        0.19752           0.18064                   -0.379467                 0.054120          0.260010            -1.830017                    17.44       17.64        17.75041            27.065853               9.378998                      0.019911                   34.399690                           0.077124                  653724.0              84.369995                      0.213023              -58.010010                      -0.107737                  -5.627799          2.827500    DPZ          6.96           1.45                      1.06                 0.215000               1.74        0.301000         Medium                    476.520                     481.93                 396.06                 538.44
3             9600.0        8.0       10.0               8.0                    7.0          9.0       0.0000  1.172  357.687500  25.895927   1059142.0            1059142.0      2043320.0            1493670.0                1493670.0   57.40     10.0      8.0  9.149989e+09            47.08             82.69                      5.054405              64.09455                        0.00                     0.000000     9.823894e+09        0.01431  156677052.0        159880992.0    7606815.0              7482389.0                  0.0476              0.01234                  1.09411        4.35               0.0869               159880992.0     16.201     3.532498       1.735603e+09       1.767139e+09         25900000.0         0.16        2.21                5.427              42.072      0.056294               68.0             1.94737                     17.0  5.573000e+08              3.486  2.335000e+08  1.231200e+09       0.137         1.021  1.810300e+09     47.498000           11.427         0.00551         0.01031  9.114000e+08  2.678125e+08       3.216000e+08          0.117       0.50345        0.12898           0.05438                   -1.919450                -0.003159         -0.001808            -1.120000                     0.16        2.21         2.27933            25.108255               0.158199                      0.002772                   -6.864552                          -0.107100                 2043320.0              10.149998                      0.215590              -25.460003                      -0.307897                   5.629384          3.274436    DAY          0.00           0.00                      0.00                 1.099000               0.00        1.250000            NaN                     56.885                      57.73                  47.08                  82.69
4            76000.0        8.0        2.0               3.0                    3.0          1.0       0.0000  1.141   13.722940  12.261757    605497.0             605497.0       891208.0             954560.0                 954560.0  136.00      8.0      9.0  1.044399e+10           131.76            179.60                      0.805333             153.93710                        0.00                     0.000000     2.416881e+10        0.06628   37882880.0         75577000.0    4841988.0              4426505.0                  0.0630              0.49776                  0.49846        5.50               0.1193                82999200.0     -3.456   -39.985530       1.735603e+09       1.767139e+09        859609984.0        10.07       11.27                1.864               9.088     -0.038143              164.0             2.90000                      9.0  5.119430e+08              6.781  2.659368e+09  1.232034e+10       1.125         1.251  1.296852e+10    742.203000          156.456         0.07041         0.54794  4.209319e+09  1.583756e+09       2.336883e+09          0.050       0.32458        0.20506           0.13443                   -0.238234                 0.000000          0.000000            -0.330002                    10.07       11.27        10.92710            12.646540              -7.220001                     -0.049653                  -15.747101                          -0.102296                  891208.0               6.430008                      0.048801              -41.410004                      -0.230568                  -3.814298          1.886800    DVA          0.00           0.00                      0.00                -0.320000               0.00       -0.245000         Medium                    136.500                     138.63                 131.76                 179.60